export const BASE_LAYOUT = [
  { text: '7' },
  { text: '8' },
  { text: '9' },
  { text: '/' },
  { text: '4' },
  { text: '5' },
  { text: '6' },
  { text: '*' },
  { text: '1' },
  { text: '2' },
  { text: '3' },
  { text: '-' },
  { text: '.' },
  { text: '0' },
  { text: '=' },
  { text: '+' },
]
